import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/utilitis/Header";

const montserrat = Montserrat({
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Vendor Match",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased h-[5000px]`}>
        <Header></Header>
        <main className="max-w-7xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
