import { Montserrat } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import SessionWrapper from "@/sessionWrapper/SessionWrapper";

const montserrat = Montserrat({
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Vendor Match",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={`${montserrat.className}  antialiased `}>
          <Toaster></Toaster>
          <main className="">{children}</main>
        </body>
      </SessionWrapper>
    </html>
  );
}
